{
    'name': 'Ninja Quiz',
    'version': '1.0',
    'summary': 'Clon de Kahoot con Odoo Surveys',
    'description': 'Permite crear quizzes interactivos como Kahoot.',
    'author': 'Michael Vahos',
    'license': 'LGPL-3',
    'depends': ['survey'],
    'data': [
        'security/ir.model.access.csv',
        "security/menu_access.xml",
        'data/ir_sequence.xml',
        'views/survey_views.xml',
        'views/survey_game_session_views.xml',
        'views/survey_game_participant_views.xml',
        'views/survey_game_participant_answer_views.xml',
        'views/kahoot_game_template.xml',
        'views/survey_question_answer_views.xml',
        'views/survey_game_views.xml',
        'views/survey_game_answer_views.xml',
    ],
    'installable': True,
    'application': True,
}
